### ISSUE TITLE
No ios to be had... Frame stuck on qr code

### ISSUE THREAD

**Issue by scotthibbs** [lomoware/lomoware.github.io#1]
I got windows, linux, android, RPi, arduino - all but mac and ios on purpose.

Don't want to use any of my phone pics, and don't mind the android app as a necessary evil. Was simply planning on adding pics to the usb directly after setup from my NAS or scanner. I would rather use the web, or windows interface - the windows upload tool is super fly since I'm scanning in pics too. I've connected using the command line (documentation needs correction to lomoware/lomorage instead of pi/raspberry) as I've needed to adjust the resolution to a salvaged laptop screen. I've added many pictures using all these methods but the frame is stuck on the QR code. 

Would it be possible to add a "bypass" (press b) key so it will continue to the pictures? Or a way to "bind" it manually since the android app is able to do it but not tell the r-pi? Maybe publish a method or file to modify/delete/create to do this. The unit seems fully functional except for the QR code. Without an ios device, I'm stuck... and I'm already in love with this software!! 

I'll be glad to do any testing needed. 
scotthibbs at g mail dot com

**Comment by aisnote** [comment]
thanks for your information, will check in detail and back to you.

**Comment by scotthibbs** [comment]
You fixed it, or my "redo" did the trick! I reflashed the card, uninstalled the app and reinstalled it and successfully binded it with the android phone. Then used the windows upload tool to put the pics I wanted on it. 

AWESOME software! Will review in Google, and share this with friends. 
Please let me know if I can help with any future testing or features. 

Thanks!
Scott
